services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: acnsms_postgres
    environment:
      POSTGRES_DB: db_of_acnsms
      POSTGRES_USER: acnsms_user
      POSTGRES_PASSWORD: acnsms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U acnsms_user -d db_of_acnsms"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acnsms_web
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://acnsms_user:acnsms_password@postgres:5432/db_of_acnsms
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python app.py

volumes:
  postgres_data:
