"""Fixed relationship conflicts

Revision ID: 509093b497ef
Revises: dfd029f47a2a
Create Date: 2025-07-21 22:28:01.658664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '509093b497ef'
down_revision = 'dfd029f47a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializePath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathCode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pathCode')
    )
    with op.batch_alter_table('specializepath', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('pathCode'))

    op.drop_table('specializepath')
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.drop_column('fullName')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('Degree', 'HND', 'Certificate'),
               nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('lecturer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('program_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('module_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('schedule_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lecturer', ['lecturer_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('subject')
        batch_op.drop_column('google_calendar_link')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')
        batch_op.drop_column('date')
        batch_op.drop_column('status')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('specializePath',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_student_specializePath'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_student_specializePath'), 'specializepath', ['specializePath'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('specializePath',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('Scheduled', 'Completed', 'Cancelled'), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('end_time', mysql.TIME(), nullable=False))
        batch_op.add_column(sa.Column('start_time', mysql.TIME(), nullable=False))
        batch_op.add_column(sa.Column('google_calendar_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('subject', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedule_ibfk_2'), 'user', ['lecturer_id'], ['id'])
        batch_op.alter_column('module_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('program_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('lecturer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('Degree', 'HND', 'Certificate'),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullName', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('name')

    op.create_table('specializepath',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pathCode', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('specializepath', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('pathCode'), ['pathCode'], unique=True)

    op.drop_table('specializePath')
    # ### end Alembic commands ###
