"""Updated program type enum

Revision ID: ac02b54ae1ab
Revises: 
Create Date: 2025-07-16 15:52:30.448934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac02b54ae1ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializePath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathCode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pathCode')
    )
    with op.batch_alter_table('specializepath', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('pathCode'))

    op.drop_table('specializepath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializepath',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('pathCode', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('specializepath', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('pathCode'), ['pathCode'], unique=True)

    op.drop_table('specializePath')
    # ### end Alembic commands ###
