"""Initial migration

Revision ID: dfd029f47a2a
Revises: ee59ba2cdab8
Create Date: 2025-07-16 16:27:27.178497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd029f47a2a'
down_revision = 'ee59ba2cdab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specializePath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathCode', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pathCode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specializePath')
    # ### end Alembic commands ###
